import React from 'react';
import './Purpose.css'
import borderimg from '../../Images/PLUR_Gradient_Line 9.png'

const Purpose = () => {
    return (
        <div className='container purpose'>
            <h1>PLUR DAO</h1>
            <h2>PURPOSE & PERKS</h2>
            <p className='mt-5'>The PLUR DAO is a collective of builders, creatives, and free-thinkers; a community that has one unified purpose: to make use of web3 tools to create a NFT platform that goes beyond making ticketing more enjoyable, accessible, secure, and unique for end end-users.</p>

            <div className="row">
                <div className="col-md-6"></div>
                <div className="col-md-6 mt-5 . d-flex">
                    <img className='d-none d-md-block pe-5' src={borderimg} alt="" />
                    <div>

                        <span className='right-text'>Plurries split the DAO revenues generated by the PLUR.systems platform in order to reward their holders and encourage long-term conviction necessary for the ecosystem to  grow & develop.</span> <br /> <br />
                        <span className='right-text '>They allow DAO members to propose any changes to the underlying governance of the NFT platform via voting, and decide on a range of matters like platform feature upgrades and community benefits.</span>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Purpose;